const defaults={"Chest":["Bench Press","Incline Dumbbell Press","Chest Press","Cable Fly"],"Back":["Lat Pulldown","Seated Cable Row","Chest Supported Row","One Arm Dumbbell Row"],"Shoulders":["Shoulder Press","Lateral Raise","Rear Delt Fly"],"Biceps":["Barbell Curl","Dumbbell Curl","Hammer Curl"],"Triceps":["Cable Pushdown","Overhead Extension","Skull Crusher"],"Legs":["Leg Press","Leg Extension","Leg Curl","Romanian Deadlift","Calf Raise"],"Abs":["Cable Crunch","Leg Raise","Plank"]};
let exercises=JSON.parse(localStorage.getItem('wt_exercises')||'null')||defaults;let logs=JSON.parse(localStorage.getItem('wt_logs')||'[]');
const $=s=>document.querySelector(s),group=$('#group'),exercise=$('#exercise'),sets=$('#sets'),date=$('#date');date.value=new Date().toISOString().slice(0,10);
function persist(){localStorage.setItem('wt_exercises',JSON.stringify(exercises));localStorage.setItem('wt_logs',JSON.stringify(logs))}
function fillGroups(){group.innerHTML=Object.keys(exercises).map(g=>`<option>${g}</option>`).join('');fillExercises()}
function fillExercises(){exercise.innerHTML=exercises[group.value].map(x=>`<option>${x}</option>`).join('');showLast();renderHistory()}
function addSet(kg='',reps=''){let n=sets.children.length+1;sets.insertAdjacentHTML('beforeend',`<tr><td>${n}</td><td><input class="setInput kg" inputmode="decimal" type="number" step="0.5" min="0" value="${kg}"></td><td><input class="setInput reps" inputmode="numeric" type="number" min="0" value="${reps}"></td><td><button class="remove" aria-label="remove">✕</button></td></tr>`)}
function renumber(){[...sets.children].forEach((r,i)=>r.children[0].textContent=i+1)}
function showLast(){let l=logs.filter(x=>x.exercise===exercise.value).sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created)[0];$('#last').textContent=l?`Τελευταία φορά (${formatDate(l.date)}): `+l.sets.map(s=>`${s.kg}kg × ${s.reps}`).join('  •  '):'Δεν υπάρχει προηγούμενη καταγραφή.'}
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('el-GR')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderHistory(){let arr=logs.filter(x=>x.group===group.value).sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);$('#history').innerHTML=arr.length?arr.map(x=>`<div class="historyItem"><div class="historyTop"><div><div class="historyTitle">${x.exercise}</div><div class="historyMeta">${formatDate(x.date)} · ${x.group}</div></div><button class="remove deleteLog" data-id="${x.id}">✕</button></div><div class="historySets">${x.sets.map((s,i)=>`S${i+1}: <b>${s.kg}kg × ${s.reps}</b>`).join(' &nbsp; ')}</div>${x.notes?`<div class="historyNotes">📝 ${escapeHtml(x.notes)}</div>`:''}</div>`).join(''):'<div class="empty">Καμία καταγραφή σε αυτή τη μυϊκή ομάδα.</div>'}
group.onchange=fillExercises;exercise.onchange=showLast;$('#addSetBtn').onclick=()=>addSet();sets.onclick=e=>{if(e.target.classList.contains('remove')){e.target.closest('tr').remove();renumber()}};
$('#saveBtn').onclick=()=>{let data=[...sets.querySelectorAll('tr')].map(r=>({kg:Number(r.querySelector('.kg').value),reps:Number(r.querySelector('.reps').value)})).filter(s=>s.kg>=0&&s.reps>0);if(!data.length)return alert('Βάλε τουλάχιστον ένα set με επαναλήψεις.');logs.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),created:Date.now(),date:date.value,group:group.value,exercise:exercise.value,sets:data,notes:$('#notes').value.trim()});persist();showLast();renderHistory();sets.innerHTML='';$('#notes').value='';addSet();addSet();addSet();};
$('#history').onclick=e=>{if(e.target.classList.contains('deleteLog')&&confirm('Διαγραφή αυτής της καταγραφής;')){logs=logs.filter(x=>x.id!==e.target.dataset.id);persist();showLast();renderHistory()}};
$('#clearBtn').onclick=()=>{if(confirm('Να διαγραφεί ΟΛΟ το ιστορικό;')){logs=[];persist();showLast();renderHistory()}};
const dlg=$('#exerciseDialog');$('#addExerciseBtn').onclick=()=>{ $('#newExercise').value='';dlg.showModal()};$('#confirmExercise').onclick=e=>{e.preventDefault();let n=$('#newExercise').value.trim();if(!n)return;if(!exercises[group.value].includes(n))exercises[group.value].push(n);persist();fillExercises();exercise.value=n;showLast();dlg.close()};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({exercises,logs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='workout-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');fillGroups();addSet();addSet();addSet();
